
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-dc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana-pod
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana-container
          image: kibana:6.4.2
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: http:elasticsearch:9200

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jenkins
#spec:
#  type: NodePort
#  ports:
#    - port: 8080
#      targetPort: 8080
#      nodePort: 30001
#  selector:
#    app: jenkins
