services:
  redis:
    image: redis
  db:
    image: postgres:9.4
  vote:
    image: voting-app
    build: ./vote
    ports:
      - 5000:80
    links:
      - redis
  result:
    image: result
    build: ./result
    ports:
      - 5001:80
    links:
      - db
  worker:
    image: worker
    build: ./worker
    links:
      - db
      - redis

#version: 2
#services:
#  redis:
#    image: redis
#    networks:
#      - back-end
#  db:
#    image: postgres:9.4
#    networks:
#      - back-end
#  vote:
#    image: voting-app
#    ports:
#      - 5000:80
#    networks:
#      - front-end
#      - back-end
#  result:
#    image: result
#    ports:
#      - 5001:80
#    networks:
#      - front-end
#      - back-end
#networks:
#  front-end:
#  back-end: