apiVersion: batch/v1
kind: Job
metadata:
  name: my-job-math-add
spec:

  completions: 3
  parallelism: 3


  template:
    spec:
      restartPolicy: Never
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '1', '+', '1']

