apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteOnly
    - ReadWriteMany

  resources:
    requests:
      storage: 500Mi
