apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteOnly
    - ReadWriteMany
  capacity:
    storage: 1Gi

  hostPath:
    path: /opt
    type: Directory
  awsElasticBlockStore:
    volumeID: <id>
    fsType: : ext4