apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  K1: V1
  # should be in encoded format ,
  # Linux  => echo -n 'text' | base64
  # decode => echo -n 'text' | base64 --decode
  K2: V2
